### ISSUE TITLE
Marble Drop DATs

### ISSUE THREAD

**Issue by sillik7** [belaw/DatPartoutExplorer#8]
This is great! Do you plan to add support for the Marble Drop DATs? The format seems to be the almost same, but the data doesn't load correctly in the tool. The only graphics I could get were the marble & text graphics in the COREA.dat, COREB.dat and COREC.dat, everything else looks to be corrupted. You can get the DATs here: https://archive.org/details/marble-drop

**Comment by belaw** [comment]
woah, I never got notified of this issue, sorry. I'm not planning on supporting Marble Drop, but I made a [010 Editor](https://www.sweetscape.com/010editor/) template that you can play around with to reverse engineer it further.
https://gist.github.com/belaw/01f22c91a7c073004096f34291943f6f
